### ISSUE TITLE
Action creates two status checks - one passes, one fails.

### ISSUE THREAD

**Issue by GabeMillikan** [travelperk/label-requires-reviews-action#524]
I have installed the action in accordance with the README.md, such that I have 3 labels:
label `a` requires 0 reviews
label `b` requires 1 reviews
label `c` requires 2 reviews

Steps to reproduce the unexpected behavior:
1. I open a PR with some changes
2. I add the `b` label (such that 1 review is required)
3. the check (titled `pull_request`) fails (expectedly, since there are no reviews) and I cannot merge
5. Someone else approves my PR
6. A _new check_ (titled `pull_request_review`) succeeds (due to the approval) **but the previous `pull_request` check is still present and failed** and I still cannot merge

![image](https://github.com/travelperk/label-requires-reviews-action/assets/44247924/006e0e56-ec81-4c69-b56a-475eed506c78)

Is it possible to fix this (without manually re-running the checks)?

<details>
  <summary>Click to see my (very standard) configuration</summary>
  
  # `.github/workflows/label-reviews.yml`
  ```yml
  # This workflow will set a number or reviewers depending on the labels
  name: Label Reviews
  # Trigger the workflow on pull requests
  on:
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
        - labeled
        - unlabeled
    pull_request_review:
      types:
        - submitted
        - edited
        - dismissed
  jobs:
    require-reviewers:
      # Optional: skip check if no relevant label is present
      # This needs to be kept in sync with the labels being checked
      runs-on: ubuntu-latest
      steps:
        - name: Require-reviewers
          uses: travelperk/label-requires-reviews-action@1.3.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            rules_yaml: | # define which PR labels require how many aprroving reviewers
              a: 0
              b: 1
              c: 2
  ```

  # repository settings
  
![image](https://github.com/travelperk/label-requires-reviews-action/assets/44247924/94e36ba4-97b6-480d-991b-55f9c0dbf89a)

</details>

**Comment by GabeMillikan** [comment]
Thank you! Is it possible to make the check re-run automatically if the tag changes?

**Comment by namelivia** [comment]
> Thank you! Is it possible to make the check re-run automatically if the tag changes?

This could work:

```
on:
  pull_request_target:
    types:
      - labeled
```
